# -*- coding: utf-8 -*-
"""Actividad N°6 Maxi Rodriguez

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1osd4Cmo5DPzOlUVD8vAbmWOAdPo4fn-M
"""

class Cuenta:

  def __init__ (self, nombre, saldo=0):
    self.nombre=nombre
    self.saldo=saldo
    if saldo < 0:
      print("saldo inicial negativo en cuenta")
      
  def mostrar(self):
    print(f"Datos de la cuenta: {self.nombre} con saldo de: {self.saldo}")

  def ingresar(self, montomas=0):
    self.montomas=montomas    
    if montomas >= 0:
      self.saldo+=self.montomas
      print("Usted depositó ", self.montomas, "y el saldo actual es de: " , self.saldo)
      return self.montomas
    
  def retirar(self, monto_retirar=0):
    self.monto_retirar=monto_retirar
    self.saldo-=self.monto_retirar
    print("Usted hizo una extracción de ", self.monto_retirar, "y el saldo actual es de:", self.saldo)
    return self.monto_retirar
      

a1 = Cuenta("Jose Luis", 20)
a1.nombre
a1.mostrar()
a1.ingresar(8)
a1.retirar(4)

